### ISSUE TITLE
Any plans to support URP v12 ? 

### ISSUE THREAD

**Issue by nukadelic** [Oculus-VR/Unity-Graphics#6]
Was hoping to see an update for this repository to a newer version to have access to Deferred Rendering Path in URP , should we anticipate this in the near future ? If not , could you suggest where to start looking when attempting something like this on my own ?

**Comment by sholms** [comment]
I really need this working on URP v12, URP v12 has a better performance impact on my game.

**Comment by nukadelic** [comment]
@sholms looks like they already do https://github.com/Oculus-VR/Unity-Graphics/tree/2021.2/oculus-app-spacewarp
